vk.access.token=vk1.a.8wqroy6AnfRbIMug3EtzwOfiBXaGqfoWDcyj2h8sITdRS3MUDjHhyUMS4Ii2vawwyOAe3R21hKVxFp05-wlPovzh5Yq_j6NuKFDK28K7oL3bB0KvdOachO-rPRCgBemHJaK3CJbmCaST7NauDchvDGabx9lxRKPuOsWlM8KCAWrpYixUFJnbdXAcKfDkYYXwvbeJmPNE99X107XJQTFt0g
vk.group.id=241870719
